// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var ctrl, drtv, ngInputDice, srvc;
    ngInputDice = angular.module('ngInputDice', []);
    srvc = ngInputDice.service('diceService', [
      '$http', function($http) {
        var serviceInterface;
        serviceInterface = this;
        console.log(serviceInterface);
        return serviceInterface;
      }
    ]);
    ctrl = ngInputDice.controller('testController', [
      '$scope', 'diceService', function($scope, diceService) {
        console.log($scope);
        return console.log(diceService);
      }
    ]);
    drtv = ngInputDice.directive('inputDice', [
      function() {
        var directiveInterface, linker;
        linker = function($scope, $element, $attrs) {
          console.log($scope);
          console.log($element);
          return console.log($attrs);
        };
        return directiveInterface = {
          controller: 'testController',
          restrict: 'E',
          scope: false,
          link: linker
        };
      }
    ]);
    return ngInputDice;
  })();

}).call(this);
